version: "2"

build:
  os: "ubuntu-22.04"
  tools:
    python: "3.8"

python:
  install:
    - requirements: requirements/docs.txt
    - requirements: requirements.txt
    - method: pip
      path: .
# sphinx:
#   fail_on_warning: true